apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-application
          image: srivarshan/sag_task:1.0.0
          env:
            - name: SECRET_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_HOST
            - name: SECRET_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_USER
            - name: SECRET_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_PASSWORD
            - name: SECRET_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_DATABASE
            - name: SECRET_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_PORT
            - name: SECRET_PORT
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: PORT
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3001
  selector:
    app: api-app
