apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app_name }}-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/behavior: '{"ScaleUp":{"StabilizationWindowSeconds":0,"Policies":[{"Type":"Pods","Value":1,"PeriodSeconds":120},{"Type":"Percent","Value":10,"PeriodSeconds":120}]},"ScaleDown":{"StabilizationWindowSeconds":0,"Policies":[{"Type":"Pods","Value":1,"PeriodSeconds":120}]}}'
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  targetCPUUtilizationPercentage: {{ .Values.cpu_utilization_limit }}
