apiVersion: {{ .Values.hpa_apiversion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app_name }}
  annotations:
   autoscaling.alpha.kubernetes.io/behavior: '{"ScaleUp":{"StabilizationWindowSeconds":0,"SelectPolicy":"Max","Policies":[{"Type":"Pods","Value":"{{ .Values.scalepod_value}}","PeriodSeconds":"{{ .Values.scale_periodsecond}}"},{"Type":"Percent","Value":"{{ .Values.scalepercent_value}}","PeriodSeconds":"{{ .Values.scale_periodsecond}}"}]},"ScaleDown":{"StabilizationWindowSeconds":0,"SelectPolicy":"Max","Policies":[{"Type":"Pods","Value":"{{ .Values.scalepod_value}}","PeriodSeconds":"{{ .Values.scale_periodsecond}}"}]}}'
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.apiversion }}
    kind: Deployment
    name: {{ .Values.app_name }}
  minReplicas: {{ .Values.scale_minreplicas }}
  maxReplicas: {{ .Values.scale_maxreplicas }}
  targetCPUUtilizationPercentage: {{ .Values.cpu_utilization_limit }}
