apiVersion: {{ .Values.apiversion }}
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: {{ .Values.app_name }}
      labels:
{{ toYaml .Values.labels | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.imageTag }}
        ports:
          - containerPort: {{ .Values.port }}
        readinessProbe:
           periodSeconds: 15
           timeoutSeconds: 2
           successThreshold: 2
           failureThreshold: 2
           httpGet:
             path: /health
             port: 80
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "500Mi"
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: DB_PASSWORD
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: DB_DATABASE
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: DB_PORT
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretFile }}
                key: PORT
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ toYaml .Values.labels | indent 6 }}
